version: "3.8"
services:
  mongodb:
    image: mongo
    container_name: mongodb
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
    - /Users/berkkayi/Desktop/my_projects/twitch_scraping/mongo_volume:/data/db
    ports:
    - 27017:27017
    restart: always